webtalk_init -webtalk_dir F:/MOHAMMED ESSAM/Digital/Design/Final_Projects/Projects/Project 1 - DSP48A1/DSP/DSP.sim/sim_1/behav/xsim/xsim.dir/tb_DSP_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Aug  3 19:56:16 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "405d681d-bb3a-46bc-a835-3b76aca6f10a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "21bf7384ed2a4bf8aecb814b31ac5fd7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "25" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "200 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6968_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1447813252 -regid "" -xml F:/MOHAMMED ESSAM/Digital/Design/Final_Projects/Projects/Project 1 - DSP48A1/DSP/DSP.sim/sim_1/behav/xsim/xsim.dir/tb_DSP_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/MOHAMMED ESSAM/Digital/Design/Final_Projects/Projects/Project 1 - DSP48A1/DSP/DSP.sim/sim_1/behav/xsim/xsim.dir/tb_DSP_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/MOHAMMED ESSAM/Digital/Design/Final_Projects/Projects/Project 1 - DSP48A1/DSP/DSP.sim/sim_1/behav/xsim/xsim.dir/tb_DSP_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
